services:
  MojoSim-Backend:
    container_name: MojoSim-Backend
    image: registry.webcase.me/node-projects/mojosim/mojosim-backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
networks:
  app-network:
    driver: bridge
