import { bool, cleanEnv, num, str, url } from 'envalid'

export const env = cleanEnv(process.env, {
  NODE_ENV: str({ choices: ['development', 'staging', 'production', 'test'] }),
  PORT: num({ default: 3000 }),
  APP_URL: url(),
  FRONTEND_URL: url(),
  FRONTEND_ADMIN_URL: str({ default: '' }),
  DB_HOST: str(),
  DB_PORT: num({ default: 5432 }),
  DB_NAME: str(),
  DB_USER: str(),
  DB_PASSWORD: str(),
  ENABLE_REDIS: bool({ default: true }),
  REDIS_URL: url(),
  JWT_SECRET: str(),
  JWT_REFRESH_SECRET: str(),
  ENCRYPTION_KEY: str(),
  STRIPE_SECRET_KEY: str(),
  STRIPE_WEBHOOK_SECRET: str(),
  PENDING_ORDER_TTL_MINUTES: num({ default: 30 }),
  AIRALO_WEBHOOK_SECRET: str(),
  SENDGRID_API_KEY: str(),
  EMAIL_FROM: str(),
  EMAIL_LOGO_URL: str({ default: '' }),
  ADMIN_EMAIL: str(),
  SUPPORT_EMAIL: str(),
  AWS_ACCESS_KEY_ID: str(),
  AWS_SECRET_ACCESS_KEY: str(),
  AWS_REGION: str(),
  AWS_S3_BUCKET_NAME: str(),
  AWS_S3_ENDPOINT: str({ default: '' }),
  AWS_S3_BASE_URL: url(),
  STORAGE_BASE_URL: url(),
  INVOICE_ISSUER_NAME: str({ default: '' }),
  USAGE_SYNC_BATCH_LIMIT: num({ default: 100 }),
  USAGE_SYNC_MIN_INTERVAL_MINUTES: num({ default: 60 }),
  USAGE_SYNC_INTER_REQUEST_DELAY_MS: num({ default: 550 }),
  AIRALO_RATE_LIMIT_RETRY_MS: num({ default: 60_000 }),
  AIRALO_PROVISION_LOOKUP_POST_DELAY_MS: num({ default: 5_000 }),
  AIRALO_MAX_REQUESTS_PER_SECOND: num({ default: 2 }),
  PROVISIONING_WORKER_CONCURRENCY: num({ default: 1 }),
  PROVISIONING_BULLMQ_ATTEMPTS: num({ default: 5 }),
  PROVISIONING_BULLMQ_BACKOFF_MS: num({ default: 60_000 }),
  AIRALO_REFUND_RATE_LIMIT_MS: num({ default: 300_000 }),
  AIRALO_REFUND_BULLMQ_ATTEMPTS: num({ default: 5 }),
  AIRALO_REFUND_BULLMQ_BACKOFF_MS: num({ default: 60_000 }),
  PLAN_SYNC_PROVISIONING_QUEUE_THRESHOLD: num({ default: 5 }),
  AUTH_COOKIE_DOMAIN: str({ default: '' }),
  TRUSTPILOT_API_KEY: str({ default: '' }),
  TRUSTPILOT_DOMAIN: str({ default: 'mojosim.com' }),
  TRUSTPILOT_CACHE_TTL_MINUTES: num({ default: 60 }),
})

export const getDatabaseUrl = (): string => {
  const encodedUser = encodeURIComponent(env.DB_USER)
  const encodedPassword = encodeURIComponent(env.DB_PASSWORD)
  return `postgres://${encodedUser}:${encodedPassword}@${env.DB_HOST}:${env.DB_PORT}/${env.DB_NAME}`
}
